### ISSUE TITLE
When will a nuget package with the current dependencies be published?

### ISSUE THREAD

**Issue by VILLAN3LL3** [oscoreio/QrCodes#18]
The SixLabors.ImageSharp version used in the current  Oscore.QrCodes.ImageSharp package version 1.0.4 has several high and medium vulnerabilities. 
The dependency is already updated in the current main branch but not yet published as nuget package.
When will the next nuget package version be published?
Thanks in advance

**Comment by HavenDV** [comment]
I have released a new version(1.0.6) using ImageSharp 2.1.9(for .Net Standard) and 3.1.5 for net6.0 and above
